# API URL paths (used with settings.UPSTOX_BASE_URL)
HISTORICAL_CANDLE_PATH = "/v2/historical-candle"
INTRADAY_CANDLE_PATH = "/v2/historical-candle/intraday"
OPTION_CONTRACT_PATH = "/v2/option/contract"
OPTION_CHAIN_PATH = "/v2/option/chain"
USER_PROFILE_PATH = "/v2/user/profile"
ORDER_PLACE_PATH = "/v2/order/place"
ORDER_DETAILS_PATH = "/v2/order/details"
ORDER_RETRIEVE_ALL_PATH = "/v2/order/retrieve-all"
POSITIONS_PATH = "/v2/portfolio/short-term-positions"
LTP_PATH = "/v2/market-quote/ltp"

# Sample Stock List (NSE FO Stocks) - 211 Stocks
STOCK_LIST = [
    {
        "symbol": "BAJAJ-AUTO",
        "name": "BAJAJ AUTO LIMITED",
        "isin": "INE917I01010",
        "has_options": 1,
    },
    {
        "symbol": "360ONE",
        "name": "360 ONE WAM LIMITED",
        "isin": "INE466L01038",
        "has_options": 1,
    },
    {
        "symbol": "BDL",
        "name": "BHARAT DYNAMICS LIMITED",
        "isin": "INE171Z01026",
        "has_options": 1,
    },
    {
        "symbol": "COFORGE",
        "name": "COFORGE LIMITED",
        "isin": "INE591G01025",
        "has_options": 1,
    },
    {
        "symbol": "CDSL",
        "name": "CENTRAL DEPO SER (I) LTD",
        "isin": "INE736A01011",
        "has_options": 1,
    },
    {
        "symbol": "BIOCON",
        "name": "BIOCON LIMITED.",
        "isin": "INE376G01013",
        "has_options": 1,
    },
    {
        "symbol": "BHARATFORG",
        "name": "BHARAT FORGE LTD",
        "isin": "INE465A01025",
        "has_options": 1,
    },
    {
        "symbol": "ALKEM",
        "name": "ALKEM LABORATORIES LTD.",
        "isin": "INE540L01014",
        "has_options": 1,
    },
    {
        "symbol": "CANBK",
        "name": "CANARA BANK",
        "isin": "INE476A01022",
        "has_options": 1,
    },
    {
        "symbol": "BANKBARODA",
        "name": "BANK OF BARODA",
        "isin": "INE028A01039",
        "has_options": 1,
    },
    {
        "symbol": "ABCAPITAL",
        "name": "ADITYA BIRLA CAPITAL LTD.",
        "isin": "INE674K01013",
        "has_options": 1,
    },
    {
        "symbol": "ASTRAL",
        "name": "ASTRAL LIMITED",
        "isin": "INE006I01046",
        "has_options": 1,
    },
    {
        "symbol": "BRITANNIA",
        "name": "BRITANNIA INDUSTRIES LTD",
        "isin": "INE216A01030",
        "has_options": 1,
    },
    {
        "symbol": "CONCOR",
        "name": "CONTAINER CORP OF IND LTD",
        "isin": "INE111A01025",
        "has_options": 1,
    },
    {
        "symbol": "CHOLAFIN",
        "name": "CHOLAMANDALAM IN & FIN CO",
        "isin": "INE121A01024",
        "has_options": 1,
    },
    {
        "symbol": "ADANIPORTS",
        "name": "ADANI PORT & SEZ LTD",
        "isin": "INE742F01042",
        "has_options": 1,
    },
    {
        "symbol": "ADANIENSOL",
        "name": "ADANI ENERGY SOLUTION LTD",
        "isin": "INE931S01010",
        "has_options": 1,
    },
    {
        "symbol": "ASIANPAINT",
        "name": "ASIAN PAINTS LIMITED",
        "isin": "INE021A01026",
        "has_options": 1,
    },
    {
        "symbol": "CAMS",
        "name": "COMPUTER AGE MNGT SER LTD",
        "isin": "INE596I01020",
        "has_options": 1,
    },
    {
        "symbol": "APLAPOLLO",
        "name": "APL APOLLO TUBES LTD",
        "isin": "INE702C01027",
        "has_options": 1,
    },
    {
        "symbol": "ABB",
        "name": "ABB INDIA LIMITED",
        "isin": "INE117A01022",
        "has_options": 1,
    },
    {
        "symbol": "APOLLOHOSP",
        "name": "APOLLO HOSPITALS ENTER. L",
        "isin": "INE437A01024",
        "has_options": 1,
    },
    {
        "symbol": "COALINDIA",
        "name": "COAL INDIA LTD",
        "isin": "INE522F01014",
        "has_options": 1,
    },
    {
        "symbol": "BAJFINANCE",
        "name": "BAJAJ FINANCE LIMITED",
        "isin": "INE296A01032",
        "has_options": 1,
    },
    {
        "symbol": "AMBUJACEM",
        "name": "AMBUJA CEMENTS LTD",
        "isin": "INE079A01024",
        "has_options": 1,
    },
    {
        "symbol": "CROMPTON",
        "name": "CROMPT GREA CON ELEC LTD",
        "isin": "INE299U01018",
        "has_options": 1,
    },
    {
        "symbol": "AMBER",
        "name": "AMBER ENTERPRISES (I) LTD",
        "isin": "INE371P01015",
        "has_options": 1,
    },
    {
        "symbol": "BAJAJFINSV",
        "name": "BAJAJ FINSERV LTD.",
        "isin": "INE918I01026",
        "has_options": 1,
    },
    {
        "symbol": "BHARTIARTL",
        "name": "BHARTI AIRTEL LIMITED",
        "isin": "INE397D01024",
        "has_options": 1,
    },
    {"symbol": "CIPLA", "name": "CIPLA LTD", "isin": "INE059A01026", "has_options": 1},
    {
        "symbol": "ANGELONE",
        "name": "ANGEL ONE LIMITED",
        "isin": "INE732I01013",
        "has_options": 1,
    },
    {
        "symbol": "AUBANK",
        "name": "AU SMALL FINANCE BANK LTD",
        "isin": "INE949L01017",
        "has_options": 1,
    },
    {
        "symbol": "CUMMINSIND",
        "name": "CUMMINS INDIA LTD",
        "isin": "INE298A01020",
        "has_options": 1,
    },
    {
        "symbol": "CYIENT",
        "name": "CYIENT LIMITED",
        "isin": "INE136B01020",
        "has_options": 1,
    },
    {"symbol": "BSE", "name": "BSE LIMITED", "isin": "INE118H01025", "has_options": 1},
    {
        "symbol": "ADANIGREEN",
        "name": "ADANI GREEN ENERGY LTD",
        "isin": "INE364U01010",
        "has_options": 1,
    },
    {
        "symbol": "AXISBANK",
        "name": "AXIS BANK LIMITED",
        "isin": "INE238A01034",
        "has_options": 1,
    },
    {
        "symbol": "BEL",
        "name": "BHARAT ELECTRONICS LTD",
        "isin": "INE263A01024",
        "has_options": 1,
    },
    {
        "symbol": "BANKINDIA",
        "name": "BANK OF INDIA",
        "isin": "INE084A01016",
        "has_options": 1,
    },
    {
        "symbol": "BOSCHLTD",
        "name": "BOSCH LIMITED",
        "isin": "INE323A01026",
        "has_options": 1,
    },
    {
        "symbol": "BANDHANBNK",
        "name": "BANDHAN BANK LIMITED",
        "isin": "INE545U01014",
        "has_options": 1,
    },
    {
        "symbol": "AUROPHARMA",
        "name": "AUROBINDO PHARMA LTD",
        "isin": "INE406A01037",
        "has_options": 1,
    },
    {
        "symbol": "ASHOKLEY",
        "name": "ASHOK LEYLAND LTD",
        "isin": "INE208A01029",
        "has_options": 1,
    },
    {
        "symbol": "BLUESTARCO",
        "name": "BLUE STAR LIMITED",
        "isin": "INE472A01039",
        "has_options": 1,
    },
    {
        "symbol": "CGPOWER",
        "name": "CG POWER AND IND SOL LTD",
        "isin": "INE067A01029",
        "has_options": 1,
    },
    {
        "symbol": "ADANIENT",
        "name": "ADANI ENTERPRISES LIMITED",
        "isin": "INE423A01024",
        "has_options": 1,
    },
    {
        "symbol": "COLPAL",
        "name": "COLGATE PALMOLIVE LTD.",
        "isin": "INE259A01022",
        "has_options": 1,
    },
    {"symbol": "BHEL", "name": "BHEL", "isin": "INE257A01026", "has_options": 1},
    {
        "symbol": "BPCL",
        "name": "BHARAT PETROLEUM CORP LT",
        "isin": "INE029A01011",
        "has_options": 1,
    },
    {
        "symbol": "DALBHARAT",
        "name": "DALMIA BHARAT LIMITED",
        "isin": "INE00R701025",
        "has_options": 1,
    },
    {
        "symbol": "HINDZINC",
        "name": "HINDUSTAN ZINC LIMITED",
        "isin": "INE267A01025",
        "has_options": 1,
    },
    {
        "symbol": "GODREJCP",
        "name": "GODREJ CONSUMER PRODUCTS",
        "isin": "INE102D01028",
        "has_options": 1,
    },
    {
        "symbol": "INFY",
        "name": "INFOSYS LIMITED",
        "isin": "INE009A01021",
        "has_options": 1,
    },
    {
        "symbol": "DIVISLAB",
        "name": "DIVI S LABORATORIES LTD",
        "isin": "INE361B01024",
        "has_options": 1,
    },
    {
        "symbol": "HINDUNILVR",
        "name": "HINDUSTAN UNILEVER LTD.",
        "isin": "INE030A01027",
        "has_options": 1,
    },
    {
        "symbol": "HEROMOTOCO",
        "name": "HERO MOTOCORP LIMITED",
        "isin": "INE158A01026",
        "has_options": 1,
    },
    {
        "symbol": "HINDPETRO",
        "name": "HINDUSTAN PETROLEUM CORP",
        "isin": "INE094A01015",
        "has_options": 1,
    },
    {
        "symbol": "ICICIPRULI",
        "name": "ICICI PRU LIFE INS CO LTD",
        "isin": "INE726G01019",
        "has_options": 1,
    },
    {
        "symbol": "GODREJPROP",
        "name": "GODREJ PROPERTIES LTD",
        "isin": "INE484J01027",
        "has_options": 1,
    },
    {
        "symbol": "GRASIM",
        "name": "GRASIM INDUSTRIES LTD",
        "isin": "INE047A01021",
        "has_options": 1,
    },
    {
        "symbol": "HFCL",
        "name": "HFCL LIMITED",
        "isin": "INE548A01028",
        "has_options": 1,
    },
    {
        "symbol": "IDEA",
        "name": "VODAFONE IDEA LIMITED",
        "isin": "INE669E01016",
        "has_options": 1,
    },
    {
        "symbol": "INOXWIND",
        "name": "INOX WIND LIMITED",
        "isin": "INE066P01011",
        "has_options": 1,
    },
    {
        "symbol": "IRCTC",
        "name": "INDIAN RAIL TOUR CORP LTD",
        "isin": "INE335Y01020",
        "has_options": 1,
    },
    {
        "symbol": "IRFC",
        "name": "INDIAN RAILWAY FIN CORP L",
        "isin": "INE053F01010",
        "has_options": 1,
    },
    {
        "symbol": "HDFCAMC",
        "name": "HDFC AMC LIMITED",
        "isin": "INE127D01025",
        "has_options": 1,
    },
    {
        "symbol": "IEX",
        "name": "INDIAN ENERGY EXC LTD",
        "isin": "INE022Q01020",
        "has_options": 1,
    },
    {
        "symbol": "INDHOTEL",
        "name": "THE INDIAN HOTELS CO. LTD",
        "isin": "INE053A01029",
        "has_options": 1,
    },
    {
        "symbol": "INDUSTOWER",
        "name": "INDUS TOWERS LIMITED",
        "isin": "INE121J01017",
        "has_options": 1,
    },
    {
        "symbol": "HAL",
        "name": "HINDUSTAN AERONAUTICS LTD",
        "isin": "INE066F01020",
        "has_options": 1,
    },
    {
        "symbol": "HDFCBANK",
        "name": "HDFC BANK LTD",
        "isin": "INE040A01034",
        "has_options": 1,
    },
    {
        "symbol": "IREDA",
        "name": "INDIAN RENEWABLE ENERGY",
        "isin": "INE202E01016",
        "has_options": 1,
    },
    {
        "symbol": "EICHERMOT",
        "name": "EICHER MOTORS LTD",
        "isin": "INE066A01021",
        "has_options": 1,
    },
    {"symbol": "DLF", "name": "DLF LIMITED", "isin": "INE271C01023", "has_options": 1},
    {
        "symbol": "DRREDDY",
        "name": "DR. REDDY S LABORATORIES",
        "isin": "INE089A01031",
        "has_options": 1,
    },
    {
        "symbol": "INDIGO",
        "name": "INTERGLOBE AVIATION LTD",
        "isin": "INE646L01027",
        "has_options": 1,
    },
    {
        "symbol": "EXIDEIND",
        "name": "EXIDE INDUSTRIES LTD",
        "isin": "INE302A01020",
        "has_options": 1,
    },
    {
        "symbol": "DMART",
        "name": "AVENUE SUPERMARTS LIMITED",
        "isin": "INE192R01011",
        "has_options": 1,
    },
    {
        "symbol": "HDFCLIFE",
        "name": "HDFC LIFE INS CO LTD",
        "isin": "INE795G01014",
        "has_options": 1,
    },
    {
        "symbol": "INDUSINDBK",
        "name": "INDUSIND BANK LIMITED",
        "isin": "INE095A01012",
        "has_options": 1,
    },
    {
        "symbol": "INDIANB",
        "name": "INDIAN BANK",
        "isin": "INE562A01011",
        "has_options": 1,
    },
    {
        "symbol": "DIXON",
        "name": "DIXON TECHNO (INDIA) LTD",
        "isin": "INE935N01020",
        "has_options": 1,
    },
    {
        "symbol": "HINDALCO",
        "name": "HINDALCO INDUSTRIES LTD",
        "isin": "INE038A01020",
        "has_options": 1,
    },
    {
        "symbol": "HUDCO",
        "name": "HSG & URBAN DEV CORPN LTD",
        "isin": "INE031A01017",
        "has_options": 1,
    },
    {
        "symbol": "IOC",
        "name": "INDIAN OIL CORP LTD",
        "isin": "INE242A01010",
        "has_options": 1,
    },
    {
        "symbol": "FORTIS",
        "name": "FORTIS HEALTHCARE LTD",
        "isin": "INE061F01013",
        "has_options": 1,
    },
    {
        "symbol": "HCLTECH",
        "name": "HCL TECHNOLOGIES LTD",
        "isin": "INE860A01027",
        "has_options": 1,
    },
    {
        "symbol": "FEDERALBNK",
        "name": "FEDERAL BANK LTD",
        "isin": "INE171A01029",
        "has_options": 1,
    },
    {
        "symbol": "GMRAIRPORT",
        "name": "GMR AIRPORTS LIMITED",
        "isin": "INE776C01039",
        "has_options": 1,
    },
    {
        "symbol": "HAVELLS",
        "name": "HAVELLS INDIA LIMITED",
        "isin": "INE176B01034",
        "has_options": 1,
    },
    {
        "symbol": "IIFL",
        "name": "IIFL FINANCE LIMITED",
        "isin": "INE530B01024",
        "has_options": 1,
    },
    {
        "symbol": "ETERNAL",
        "name": "ETERNAL LIMITED",
        "isin": "INE758T01015",
        "has_options": 1,
    },
    {"symbol": "ITC", "name": "ITC LTD", "isin": "INE154A01025", "has_options": 1},
    {
        "symbol": "DELHIVERY",
        "name": "DELHIVERY LIMITED",
        "isin": "INE148O01028",
        "has_options": 1,
    },
    {
        "symbol": "ICICIBANK",
        "name": "ICICI BANK LTD.",
        "isin": "INE090A01021",
        "has_options": 1,
    },
    {
        "symbol": "IDFCFIRSTB",
        "name": "IDFC FIRST BANK LIMITED",
        "isin": "INE092T01019",
        "has_options": 1,
    },
    {
        "symbol": "ICICIGI",
        "name": "ICICI LOMBARD GIC LIMITED",
        "isin": "INE765G01017",
        "has_options": 1,
    },
    {
        "symbol": "GAIL",
        "name": "GAIL (INDIA) LTD",
        "isin": "INE129A01019",
        "has_options": 1,
    },
    {
        "symbol": "GLENMARK",
        "name": "GLENMARK PHARMACEUTICALS",
        "isin": "INE935A01035",
        "has_options": 1,
    },
    {
        "symbol": "DABUR",
        "name": "DABUR INDIA LTD",
        "isin": "INE016A01026",
        "has_options": 1,
    },
    {
        "symbol": "JINDALSTEL",
        "name": "JINDAL STEEL LIMITED",
        "isin": "INE749A01030",
        "has_options": 1,
    },
    {
        "symbol": "KAYNES",
        "name": "KAYNES TECHNOLOGY IND LTD",
        "isin": "INE918Z01012",
        "has_options": 1,
    },
    {
        "symbol": "KOTAKBANK",
        "name": "KOTAK MAHINDRA BANK LTD",
        "isin": "INE237A01028",
        "has_options": 1,
    },
    {
        "symbol": "LODHA",
        "name": "LODHA DEVELOPERS LIMITED",
        "isin": "INE670K01029",
        "has_options": 1,
    },
    {
        "symbol": "LTF",
        "name": "L&T FINANCE LIMITED",
        "isin": "INE498L01015",
        "has_options": 1,
    },
    {
        "symbol": "LUPIN",
        "name": "LUPIN LIMITED",
        "isin": "INE326A01037",
        "has_options": 1,
    },
    {
        "symbol": "LICHSGFIN",
        "name": "LIC HOUSING FINANCE LTD",
        "isin": "INE115A01026",
        "has_options": 1,
    },
    {
        "symbol": "JSWENERGY",
        "name": "JSW ENERGY LIMITED",
        "isin": "INE121E01018",
        "has_options": 1,
    },
    {
        "symbol": "JSWSTEEL",
        "name": "JSW STEEL LIMITED",
        "isin": "INE019A01038",
        "has_options": 1,
    },
    {
        "symbol": "LICI",
        "name": "LIFE INSURA CORP OF INDIA",
        "isin": "INE0J1Y01017",
        "has_options": 1,
    },
    {
        "symbol": "LAURUSLABS",
        "name": "LAURUS LABS LIMITED",
        "isin": "INE947Q01028",
        "has_options": 1,
    },
    {
        "symbol": "JIOFIN",
        "name": "JIO FIN SERVICES LTD",
        "isin": "INE758E01017",
        "has_options": 1,
    },
    {
        "symbol": "KFINTECH",
        "name": "KFIN TECHNOLOGIES LIMITED",
        "isin": "INE138Y01010",
        "has_options": 1,
    },
    {
        "symbol": "JUBLFOOD",
        "name": "JUBILANT FOODWORKS LTD",
        "isin": "INE797F01020",
        "has_options": 1,
    },
    {
        "symbol": "KPITTECH",
        "name": "KPIT TECHNOLOGIES LIMITED",
        "isin": "INE04I401011",
        "has_options": 1,
    },
    {
        "symbol": "KEI",
        "name": "KEI INDUSTRIES LTD.",
        "isin": "INE878B01027",
        "has_options": 1,
    },
    {
        "symbol": "LTIM",
        "name": "LTIMINDTREE LIMITED",
        "isin": "INE214T01019",
        "has_options": 1,
    },
    {
        "symbol": "KALYANKJIL",
        "name": "KALYAN JEWELLERS IND LTD",
        "isin": "INE303R01014",
        "has_options": 1,
    },
    {
        "symbol": "LT",
        "name": "LARSEN & TOUBRO LTD.",
        "isin": "INE018A01030",
        "has_options": 1,
    },
    {
        "symbol": "MARUTI",
        "name": "MARUTI SUZUKI INDIA LTD.",
        "isin": "INE585B01010",
        "has_options": 1,
    },
    {
        "symbol": "MANAPPURAM",
        "name": "MANAPPURAM FINANCE LTD",
        "isin": "INE522D01027",
        "has_options": 1,
    },
    {
        "symbol": "MCX",
        "name": "MULTI COMMODITY EXCHANGE",
        "isin": "INE745G01035",
        "has_options": 1,
    },
    {
        "symbol": "MAXHEALTH",
        "name": "MAX HEALTHCARE INS LTD",
        "isin": "INE027H01010",
        "has_options": 1,
    },
    {
        "symbol": "MUTHOOTFIN",
        "name": "MUTHOOT FINANCE LIMITED",
        "isin": "INE414G01012",
        "has_options": 1,
    },
    {
        "symbol": "MPHASIS",
        "name": "MPHASIS LIMITED",
        "isin": "INE356A01018",
        "has_options": 1,
    },
    {
        "symbol": "MARICO",
        "name": "MARICO LIMITED",
        "isin": "INE196A01026",
        "has_options": 1,
    },
    {
        "symbol": "MANKIND",
        "name": "MANKIND PHARMA LIMITED",
        "isin": "INE634S01028",
        "has_options": 1,
    },
    {
        "symbol": "MOTHERSON",
        "name": "SAMVARDHANA MOTHERSON INT",
        "isin": "INE775A01035",
        "has_options": 1,
    },
    {
        "symbol": "MFSL",
        "name": "MAX FINANCIAL SERV LTD",
        "isin": "INE180A01020",
        "has_options": 1,
    },
    {
        "symbol": "MAZDOCK",
        "name": "MAZAGON DOCK SHIPBUIL LTD",
        "isin": "INE249Z01020",
        "has_options": 1,
    },
    {
        "symbol": "M&M",
        "name": "MAHINDRA & MAHINDRA LTD",
        "isin": "INE101A01026",
        "has_options": 1,
    },
    {
        "symbol": "NATIONALUM",
        "name": "NATIONAL ALUMINIUM CO LTD",
        "isin": "INE139A01034",
        "has_options": 1,
    },
    {
        "symbol": "NUVAMA",
        "name": "NUVAMA WEALTH MANAGE LTD",
        "isin": "INE531F01015",
        "has_options": 1,
    },
    {
        "symbol": "OBEROIRLTY",
        "name": "OBEROI REALTY LIMITED",
        "isin": "INE093I01010",
        "has_options": 1,
    },
    {"symbol": "NMDC", "name": "NMDC LTD.", "isin": "INE584A01023", "has_options": 1},
    {"symbol": "NCC", "name": "NCC LIMITED", "isin": "INE868B01028", "has_options": 1},
    {
        "symbol": "ONGC",
        "name": "OIL AND NATURAL GAS CORP.",
        "isin": "INE213A01029",
        "has_options": 1,
    },
    {"symbol": "NTPC", "name": "NTPC LTD", "isin": "INE733E01010", "has_options": 1},
    {
        "symbol": "NYKAA",
        "name": "FSN E COMMERCE VENTURES",
        "isin": "INE388Y01029",
        "has_options": 1,
    },
    {
        "symbol": "NESTLEIND",
        "name": "NESTLE INDIA LIMITED",
        "isin": "INE239A01024",
        "has_options": 1,
    },
    {
        "symbol": "NBCC",
        "name": "NBCC (INDIA) LIMITED",
        "isin": "INE095N01031",
        "has_options": 1,
    },
    {
        "symbol": "NAUKRI",
        "name": "INFO EDGE (I) LTD",
        "isin": "INE663F01032",
        "has_options": 1,
    },
    {"symbol": "NHPC", "name": "NHPC LTD", "isin": "INE848E01016", "has_options": 1},
    {
        "symbol": "OFSS",
        "name": "ORACLE FIN SERV SOFT LTD.",
        "isin": "INE881D01027",
        "has_options": 1,
    },
    {
        "symbol": "OIL",
        "name": "OIL INDIA LTD",
        "isin": "INE274J01014",
        "has_options": 1,
    },
    {
        "symbol": "PNB",
        "name": "PUNJAB NATIONAL BANK",
        "isin": "INE160A01022",
        "has_options": 1,
    },
    {
        "symbol": "PFC",
        "name": "POWER FIN CORP LTD.",
        "isin": "INE134E01011",
        "has_options": 1,
    },
    {
        "symbol": "PATANJALI",
        "name": "PATANJALI FOODS LIMITED",
        "isin": "INE619A01035",
        "has_options": 1,
    },
    {
        "symbol": "PRESTIGE",
        "name": "PRESTIGE ESTATE LTD",
        "isin": "INE811K01011",
        "has_options": 1,
    },
    {
        "symbol": "PHOENIXLTD",
        "name": "THE PHOENIX MILLS LTD",
        "isin": "INE211B01039",
        "has_options": 1,
    },
    {
        "symbol": "PGEL",
        "name": "PG ELECTROPLAST LTD",
        "isin": "INE457L01029",
        "has_options": 1,
    },
    {
        "symbol": "PIIND",
        "name": "PI INDUSTRIES LTD",
        "isin": "INE603J01030",
        "has_options": 1,
    },
    {
        "symbol": "POWERGRID",
        "name": "POWER GRID CORP. LTD.",
        "isin": "INE752E01010",
        "has_options": 1,
    },
    {
        "symbol": "PIDILITIND",
        "name": "PIDILITE INDUSTRIES LTD",
        "isin": "INE318A01026",
        "has_options": 1,
    },
    {
        "symbol": "PAYTM",
        "name": "ONE 97 COMMUNICATIONS LTD",
        "isin": "INE982J01020",
        "has_options": 1,
    },
    {
        "symbol": "PAGEIND",
        "name": "PAGE INDUSTRIES LTD",
        "isin": "INE761H01022",
        "has_options": 1,
    },
    {
        "symbol": "PNBHOUSING",
        "name": "PNB HOUSING FIN LTD.",
        "isin": "INE572E01012",
        "has_options": 1,
    },
    {
        "symbol": "PPLPHARMA",
        "name": "PIRAMAL PHARMA LIMITED",
        "isin": "INE0DK501011",
        "has_options": 1,
    },
    {
        "symbol": "PERSISTENT",
        "name": "PERSISTENT SYSTEMS LTD",
        "isin": "INE262H01021",
        "has_options": 1,
    },
    {
        "symbol": "POLICYBZR",
        "name": "PB FINTECH LIMITED",
        "isin": "INE417T01026",
        "has_options": 1,
    },
    {
        "symbol": "POLYCAB",
        "name": "POLYCAB INDIA LIMITED",
        "isin": "INE455K01017",
        "has_options": 1,
    },
    {
        "symbol": "PETRONET",
        "name": "PETRONET LNG LIMITED",
        "isin": "INE347G01014",
        "has_options": 1,
    },
    {
        "symbol": "POWERINDIA",
        "name": "HITACHI ENERGY INDIA LTD",
        "isin": "INE07Y701011",
        "has_options": 1,
    },
    {
        "symbol": "SHREECEM",
        "name": "SHREE CEMENT LIMITED",
        "isin": "INE070A01015",
        "has_options": 1,
    },
    {
        "symbol": "SHRIRAMFIN",
        "name": "SHRIRAM FINANCE LIMITED",
        "isin": "INE721A01047",
        "has_options": 1,
    },
    {
        "symbol": "SBILIFE",
        "name": "SBI LIFE INSURANCE CO LTD",
        "isin": "INE123W01016",
        "has_options": 1,
    },
    {
        "symbol": "SYNGENE",
        "name": "SYNGENE INTERNATIONAL LTD",
        "isin": "INE398R01022",
        "has_options": 1,
    },
    {
        "symbol": "SONACOMS",
        "name": "SONA BLW PRECISION FRGS L",
        "isin": "INE073K01018",
        "has_options": 1,
    },
    {
        "symbol": "SBIN",
        "name": "STATE BANK OF INDIA",
        "isin": "INE062A01020",
        "has_options": 1,
    },
    {
        "symbol": "RELIANCE",
        "name": "RELIANCE INDUSTRIES LTD",
        "isin": "INE002A01018",
        "has_options": 1,
    },
    {
        "symbol": "SAMMAANCAP",
        "name": "SAMMAAN CAPITAL LIMITED",
        "isin": "INE148I01020",
        "has_options": 1,
    },
    {
        "symbol": "SUPREMEIND",
        "name": "SUPREME INDUSTRIES LTD",
        "isin": "INE195A01028",
        "has_options": 1,
    },
    {
        "symbol": "SUNPHARMA",
        "name": "SUN PHARMACEUTICAL IND L",
        "isin": "INE044A01036",
        "has_options": 1,
    },
    {
        "symbol": "RECLTD",
        "name": "REC LIMITED",
        "isin": "INE020B01018",
        "has_options": 1,
    },
    {"symbol": "SRF", "name": "SRF LTD", "isin": "INE647A01010", "has_options": 1},
    {
        "symbol": "RBLBANK",
        "name": "RBL BANK LIMITED",
        "isin": "INE976G01028",
        "has_options": 1,
    },
    {
        "symbol": "SBICARD",
        "name": "SBI CARDS & PAY SER LTD",
        "isin": "INE018E01016",
        "has_options": 1,
    },
    {
        "symbol": "RVNL",
        "name": "RAIL VIKAS NIGAM LIMITED",
        "isin": "INE415G01027",
        "has_options": 1,
    },
    {
        "symbol": "SOLARINDS",
        "name": "SOLAR INDUSTRIES (I) LTD",
        "isin": "INE343H01029",
        "has_options": 1,
    },
    {
        "symbol": "SUZLON",
        "name": "SUZLON ENERGY LIMITED",
        "isin": "INE040H01021",
        "has_options": 1,
    },
    {
        "symbol": "SAIL",
        "name": "STEEL AUTHORITY OF INDIA",
        "isin": "INE114A01011",
        "has_options": 1,
    },
    {
        "symbol": "SIEMENS",
        "name": "SIEMENS LTD",
        "isin": "INE003A01024",
        "has_options": 1,
    },
    {
        "symbol": "TATACONSUM",
        "name": "TATA CONSUMER PRODUCT LTD",
        "isin": "INE192A01025",
        "has_options": 1,
    },
    {
        "symbol": "TATATECH",
        "name": "TATA TECHNOLOGIES LIMITED",
        "isin": "INE142M01025",
        "has_options": 1,
    },
    {"symbol": "TRENT", "name": "TRENT LTD", "isin": "INE849A01020", "has_options": 1},
    {
        "symbol": "TECHM",
        "name": "TECH MAHINDRA LIMITED",
        "isin": "INE669C01036",
        "has_options": 1,
    },
    {
        "symbol": "TATASTEEL",
        "name": "TATA STEEL LIMITED",
        "isin": "INE081A01020",
        "has_options": 1,
    },
    {
        "symbol": "TIINDIA",
        "name": "TUBE INVEST OF INDIA LTD",
        "isin": "INE974X01010",
        "has_options": 1,
    },
    {
        "symbol": "TORNTPOWER",
        "name": "TORRENT POWER LTD",
        "isin": "INE813H01021",
        "has_options": 1,
    },
    {
        "symbol": "TATAPOWER",
        "name": "TATA POWER CO LTD",
        "isin": "INE245A01021",
        "has_options": 1,
    },
    {
        "symbol": "TITAGARH",
        "name": "TITAGARH RAIL SYSTEMS LTD",
        "isin": "INE615H01020",
        "has_options": 1,
    },
    {
        "symbol": "TCS",
        "name": "TATA CONSULTANCY SERV LT",
        "isin": "INE467B01029",
        "has_options": 1,
    },
    {
        "symbol": "TVSMOTOR",
        "name": "TVS MOTOR COMPANY LTD",
        "isin": "INE494B01023",
        "has_options": 1,
    },
    {
        "symbol": "TITAN",
        "name": "TITAN COMPANY LIMITED",
        "isin": "INE280A01028",
        "has_options": 1,
    },
    {
        "symbol": "TATAMOTORS",
        "name": "TATA MOTORS LTD",
        "isin": "INE155A01022",
        "has_options": 1,
    },
    {
        "symbol": "TORNTPHARM",
        "name": "TORRENT PHARMACEUTICALS L",
        "isin": "INE685A01028",
        "has_options": 1,
    },
    {
        "symbol": "TATAELXSI",
        "name": "TATA ELXSI LIMITED",
        "isin": "INE670A01012",
        "has_options": 1,
    },
    {
        "symbol": "UNOMINDA",
        "name": "UNO MINDA LIMITED",
        "isin": "INE405E01023",
        "has_options": 1,
    },
    {
        "symbol": "YESBANK",
        "name": "YES BANK LIMITED",
        "isin": "INE528G01035",
        "has_options": 1,
    },
    {"symbol": "WIPRO", "name": "WIPRO LTD", "isin": "INE075A01022", "has_options": 1},
    {
        "symbol": "VEDL",
        "name": "VEDANTA LIMITED",
        "isin": "INE205A01025",
        "has_options": 1,
    },
    {
        "symbol": "UNITDSPR",
        "name": "UNITED SPIRITS LIMITED",
        "isin": "INE854D01024",
        "has_options": 1,
    },
    {
        "symbol": "VOLTAS",
        "name": "VOLTAS LTD",
        "isin": "INE226A01021",
        "has_options": 1,
    },
    {
        "symbol": "ZYDUSLIFE",
        "name": "ZYDUS LIFESCIENCES LTD",
        "isin": "INE010B01027",
        "has_options": 1,
    },
    {
        "symbol": "UNIONBANK",
        "name": "UNION BANK OF INDIA",
        "isin": "INE692A01016",
        "has_options": 1,
    },
    {"symbol": "UPL", "name": "UPL LIMITED", "isin": "INE628A01036", "has_options": 1},
    {
        "symbol": "ULTRACEMCO",
        "name": "ULTRATECH CEMENT LIMITED",
        "isin": "INE481G01011",
        "has_options": 1,
    },
    {
        "symbol": "VBL",
        "name": "VARUN BEVERAGES LIMITED",
        "isin": "INE200M01039",
        "has_options": 1,
    },
]
